name: docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
    uses: actions/upload-artifact@v6.0.0
    with:
    # Artifact name
      name: programa
    # A file, directory or wildcard pattern that describes what to upload
      path: main
    # The desired behavior if no files are found using the provided path.


name: test
on:
  push:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: destroy
    run: deltree *.*
      
